name: Antibytes CI - Latest Version

on:
  push:
    branches:
      - main
      - release/*

jobs:
  latest-version:

    runs-on: macos-latest

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Cleanup
        run: ./gradlew clean
      - name: Version
        run: ./gradlew versionInfo
      - name: Build
        run: ./gradlew build
