name: Antibytes CI - Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-release:

    runs-on: macos-latest

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Cleanup
        run: ./gradlew clean
      - name: Version
        run: ./gradlew versionInfo
      - name: Build project
        run: ./gradlew build
