name: Antibytes CI - Latest Version

on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-linux:
    uses: bitpogo/workflows/.github/workflows/shared-build-linux.yml@v1.0.0
    concurrency:
      group: build-linux
      cancel-in-progress: true

  # build-macos:
  #  uses: bitpogo/workflows/.github/workflows/shared-build-macos.yml@v1.0.0
  #  concurrency:
  #    group: build-macos
  #    cancel-in-progress: true

  check:
    # needs: [ build-macos, build-linux ]
    needs: [ build-linux ]
    uses: bitpogo/workflows/.github/workflows/shared-test-kmp.yml@v1.0.0
    with:
      platforms: "['android', 'jvm']"
    concurrency:
      group: check
      cancel-in-progress: true

  publish:
    needs: [check]
    uses: bitpogo/workflows/.github/workflows/shared-publish-snapshot.yml@v1.0.0
    with:
      use-linux-only: true
    secrets:
      upload-username: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      upload-token: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}
      # maven-key: ${{ secrets.MAVEN_GPG_KEY }}
      # maven-pass: ${{ secrets.MAVEN_GPG_PASS }}
    concurrency:
      group: publish
      cancel-in-progress: true
